name: Build
on: [push]

jobs:
  lint:
    name: Lint/Test
    # This job runs on Linux
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [ '8', '9', '10', '11', '12' ]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install DEV dependencies
        run: npm i
      - name: Tests
        run: make test
      - name: Lint
        run: make lint
